# Generated by Django 5.2.1 on 2025-05-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list, help_text='List of ingredients from predefined choices'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.JSONField(default=list, help_text='List of quantities (numbers only)'),
        ),
    ]
