# Generated by Django 5.2.1 on 2025-05-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_ingredients_alter_recipe_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.JSONField(default=list),
        ),
    ]
