# Generated by Django 5.2.1 on 2025-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0002_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('course_type', models.CharField(choices=[('appetizer', 'Appetizer'), ('main course', 'Main Course'), ('dessert', 'Dessert'), ('snack', 'Snack')], max_length=20)),
                ('time', models.IntegerField(help_text='Cooking time in minutes')),
                ('food_type', models.CharField(choices=[('Italian', 'Italian'), ('SeaFood', 'SeaFood'), ('Meat', 'Meat'), ('Vegetarian', 'Vegetarian'), ('Desserts', 'Desserts')], max_length=20)),
                ('ingredients', models.JSONField(default=list)),
                ('quantity', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
