name: recipe-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asgiref=3.8.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - django=5.2
  - expat=2.7.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - idna=3.7
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libpng=1.6.39
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=11.1.0
  - pip=25.1
  - pysocks=1.7.1
  - python=3.13.2
  - python_abi=3.13
  - requests=2.32.3
  - setuptools=78.1.1
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - cloudinary==1.44.0
      - django-cloudinary-storage==0.3.0
      - django-sslserver==0.22
      - docutils==0.21.2
      - mailersend==0.6.0
      - six==1.17.0
