# Generated by Django 5.2 on 2025-05-16 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('incorrect-info', 'Incorrect Recipe Information'), ('missing-recipe', 'Missing Recipe'), ('technical-issue', 'Technical Issue'), ('copyright', 'Copyright Concern'), ('other', 'Other')], max_length=20, verbose_name='Type of Report')),
                ('description', models.TextField(verbose_name='Description of the Problem')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='report_screenshots/', verbose_name='Screenshot')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reporter Email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Report Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
