# Generated by Django 5.2.1 on 2025-05-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='screenshot',
            field=models.URLField(blank=True, null=True, verbose_name='Screenshot URL'),
        ),
    ]
