# Generated by Django 5.2.1 on 2025-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_report_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='report',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
