# Generated by Django 5.2.1 on 2025-05-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.IntegerField(choices=[(0, 'User'), (-1, 'Admin'), (1, 'Admin')], default=0),
        ),
    ]
